apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-feet
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: luke0195/reactapp
          ports:
            - containerPort: 8000
